version: '3.8'

services:
  test-bot:
    build: .
    container_name: express_bot_test
    restart: always
    ports:
      - "${PORT_OUT:-8110}:3000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - test_data:/app/data

volumes:
  test_data:
